{{- if .Values.crons }}
{{- range .Values.crons }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ print $.Release.Name "-cronjob-" .name | replace " " "-" | replace "_" "-" }}
  labels:
    app: {{ $.Release.Name }}
spec:
  schedule: "{{ .schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ print $.Release.Name "-cronjob-" .name | replace " " "-" | replace "_" "-" }}
            image: "{{ $.Values.images.rails.repository }}:{{ $.Values.images.rails.tag }}"
            imagePullPolicy: {{ $.Values.images.rails.pullPolicy }}
            args: 
            {{- range .command }}
              - {{ . }}
            {{- end }}
            envFrom:
            - configMapRef:
                name: {{ $.Release.Name }}-env
          restartPolicy: OnFailure
{{- end }}
{{- end }}
