apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-{{ .Release.Name }}
  labels:
    alicloud-pvname: pv-{{ .Release.Name }}
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: nasplugin.csi.alibabacloud.com
    volumeHandle: pv-{{ .Release.Name }}
    volumeAttributes:
      server: {{ .Values.nas.server }}
      path: {{ .Values.nas.path }}
      vers: "3"