apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-{{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  # storageClassName: nas
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      alicloud-pvname: pv-{{ .Release.Name }}